### ISSUE TITLE
can not access to the data

### ISSUE THREAD

**Issue by KarlQu1990** [prafulla77/TAC-KBP-2017-Participation#1]
HI, @prafulla77 , can you please upload few samples of  training data  in case I can understand the data processing code and try to reproduce your result? 
thanks.

**Comment by prafulla77** [comment]
I am sorry! I can't upload any instance of the KBP corpus as per the data-use-agreement.

**Comment by KarlQu1990** [comment]
Are there any similar open source corpus which have the same annotated structure? I google a lot, but get no clue. 
thanks.

**Comment by prafulla77** [comment]
Probably you can register for KBP 2018 and get the corpus. 
Here is a snapshot of the annotation file.
`<hoppers>
    <hopper id="h-8">
      <event_mention id="xx" type="xx" subtype="xx" realis="xx" ways="xx">
        <trigger source="file name" offset="--" length="--">ooo</trigger>
      </event_mention>
      <event_mention id="xx" type="xx" subtype="xx" realis="xx" ways="xx">
        <trigger source="file name" offset="--" length="--">ooo</trigger>
      </event_mention>
      <event_mention id="xx" type="xx" subtype="xx" realis="xx" ways="xx">
        <trigger source="file name" offset="--" length="--">ooo</trigger>
      </event_mention>
      <event_mention id="xx" type="xx" subtype="xx" realis="xx" ways="xx">
        <trigger source="file name" offset="--" length="--">ooo</trigger>
      </event_mention>
    </hopper>`

**Comment by KarlQu1990** [comment]
Ok, I will try. Thanks a lot!
