### ISSUE TITLE
could not run ensemble_classifier_test.py .

### ISSUE THREAD

**Issue by rainbow7xj** [prafulla77/TAC-KBP-2017-Participation#2]
hello @prafulla77 ,i got an error when i run ensemble_classifier_test.py
```
Traceback (most recent call last):
  File "ensemble_classifier_test.py", line 17, in <module>
    with open('../vocab/2017_.pkl', 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '../vocab/2017_.pkl'
```
how can i get the file?
thanks a lot.

**Comment by rashmisankepally** [comment]
I have the same problem. How should access the vocab folder? 

Thanking you,
Rashmi

**Comment by prafulla77** [comment]
2017_.pkl is just a dictionary of word vectors (use glove.840B.300d). You should create your own based on the test dataset you are using. 
Format:
{'i':[1.2, -0.4, ........], 'was':300d vector, ......}

You can find the embeddings for data used in this experiment @ https://drive.google.com/file/d/1KT-be3zTNBIXMRggdRcyn5ZfuoD2Ikj4/view?usp=sharing
